#!/bin/sh
alt {_,shift + } Return
			{st,st -c CenterTerminal}

alt + {d,r,p,e}
		rofi -show {drun,run,window,emoji} -show-icons

alt + n
		rofisearcher
alt + s
		scrot -b -d 5 '%Y:%m:%d:%H:%M:%S.png'

alt + shift {e,w,n}
		~/dotfiles/exts/{logout,words,ipa} &

alt + {g,y}
		~/dotfiles/exts/{class,yt}

shift + {p,w,n}
		~/dotfiles/exts/{pauseaudio,wp}

shift {u,d,m}
		amixer set Master {3+,3-,toggle};

shift + q
		pkill mpv; pkill sxiv

shift + {z,x}
		xbacklight {-dec,-inc} 5

ctrl + alt + {h, j, k,}
		bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

alt {_,shift + } f
		bspc node -t {floating,fullscreen}

alt {_,shift + } q
		bspc node -{c,k}

alt + {t,shift + t}
		bspc node -t {tiled, pseudo_tiled}

alt + ctrl + {m,l,s,p}
		bspc node -g {marked,locked,sticky,private}

alt + {_,shift + }{Left,Down,Up,Right}
		bspc node -{f,s} {west,south,north,east}

alt + {_,shift + }{1-9,0}
		bspc {desktop -f,node -d} '^{1-9,10}';

alt + ctrl + {Left,Down,Up,Right}
		bspc node -v {-20 0,0 20,0 -20,20 0}
