#!/bin/sh
#Adapted to the NCVS dialect.
Symbols="
–  | -
dʒ | dj
tʃ | ch
ə  | uh
ä  | a
ɛ | e
ɚ  | ur 
ɑ˞ | ar
ɔ˞ | or
eə  | ea
ð  | dth
ā | ei
ē  | ee
ī   | ai
ŋ  | ng
ō  | ow
äʉ | aw
ɒ  | o
ɔɪ | oi
ɪ | ih
ɫ  | l
ɱ  | m]
ɸ  | f]
ɹ  | rr
ɾ  | dd
ʃ  | sh
ʊ  | uh
ʒ  | zh
ʔ  | glottal ?
ʰ  | h_
β  | v]
θ  | th
—  | --
→  | ->
n̩ | n
ɵ | oh
"
echo "$Symbols" | dmenu -i -l 10 | awk '{print $1}' | tr -d '\n' | xclip -selection clipboard
notify-send "$(xclip -o -selection clipboard) copied to clipboard"
