#!/bin/sh
Symbols="
–  | -
dʒ | dj
tʃ | ch
ə  | uh
ä  | a
ɛ | e
eə  | ea
ð  | dth
ŋ  | ng
ɑ| o
ɪ | ih
ɫ  | l
ɱ  | m]
ɸ  | f]
ɹ  | rr
ɾ  | dd
ʃ  | sh
ʊ  | uh
ʒ  | zh
ʔ  | glottal ?
ʰ  | h_
β  | v]
θ  | th
—  | --
→  | ->"
echo "$Symbols" | dmenu -i -l 10 | awk '{print $1}' | tr -d '\n' | xclip -selection clipboard
notify-send "$(xclip -o -selection clipboard) copied to clipboard"
